fix: mark resultIds as non-database field and remove related update logic
Fixed another database field mismatch error for result_ids column.

Changes:
1. ModelExecutionRecord entity:
   - Added @TableField(exist = false) to resultIds field
   - This field doesn't exist in model_execution_record table

2. ModelExecutionServiceImpl:
   - Removed code that collects resultIds from evaluation results
   - Removed updateById() call that tried to update resultIds
   - Removed setResultCount() call as this field also doesn't exist in DB
   - Simplified save logic to only insert evaluation results

This fixes the error:
SQLSyntaxErrorException: Unknown column 'result_ids' in 'field list'

Note: Both resultIds and resultCount are kept in entity for potential
future use but marked as non-database fields.